geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.index, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('<int:pk>/', mainapp.products, name='category'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='название')
    description = models.TextField(blank=True, null=True, verbose_name='описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('-id',)


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products', blank=True, null=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=256, verbose_name='краткое описание')
    description = models.TextField(blank=True, null=True, verbose_name='описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='количество')
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')

    def __str__(self):
        return f'{self.name} | {self.category.name}'

geekshop/mainapp/views.py
from django.shortcuts import render

from mainapp.models import Product, ProductCategory


def index(request):
    context = {
        'title':'Главная',
        'products': Product.objects.all(),
    }
    return render(request, 'mainapp/index.html',context)


def contact(request):
    context = {
        'title': 'Контакты',
    }
    return render(request, 'mainapp/contact.html',context)

def products(request, pk=None):
    context = {
        'title':'Продукты',
        'links_menu': ProductCategory.objects.all()
    }
    return render(request, 'mainapp/products.html', context=context)

geekshop/mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}{{ title }}{% endblock %}</title>
    {% block css %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="container">
        {% block menu %}

        {% endblock %}

        {% block content %}
        {% endblock %}

		<div class="clr"></div>

	</div>
{% block footer %}
	<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}
</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block menu %}
    <div class="hero">
        <div class="header clearfix">
            <a href="index.html" class="logo"></a>
            <ul class="menu">
                {% include 'mainapp/includes/inc_main_menu.html' %}
            </ul>
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
        <h1>наши контакты</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="location">
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li><a href="{% url 'products:products' %}">Все</a></li>
    {% for item_link in links_menu %}
        <li><a
                href="{% url 'products:category' item_link.pk %}"
                {% if request.resolver_match.url_name == item_link.url %} class="active"{% endif %}
        >{{ item_link.name }}</a></li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
<li><a href="{% url 'index' %}" {% if request.resolver_match.url_name == 'index' %} class="active"{% endif %}>домой</a>
</li>
<li><a href="{% url 'products:products' %}"{% if 'products' in request.resolver_match.url_name %} class="active"{% endif %}>продукты</a>
</li>
<li><a href="{% url 'contact' %}"{% if request.resolver_match.url_name == 'contact' %} class="active"{% endif %}">контакты</a>
</li>

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% load static %}
{% block menu %}
    <div class="slider">
        <div class="header clearfix">
            <a href="index.html" class="logo"></a>
            <ul class="menu">
               {% include 'mainapp/includes/inc_main_menu.html' %}
            </ul>
            <a href="#" class="search"></a>
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            <div class="block">
                <a href="#"><img src="{% static 'img/product-1.jpg' %}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="img">
                        <h4>Отличный стул</h4>
                        <p>Расположитесь комфортно. </p>
                    </div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="{% static 'img/product-2.jpg' %}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="">
                        <h4>Стул повышенного качества</h4>
                        <p>Не оторваться. </p>
                    </div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            <a href="index.html" class="logo"></a>
            <ul class="menu">
                {% include 'mainapp/includes/inc_main_menu.html' %}

            </ul>
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html'%}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{% static 'img/slider1.jpg' %}">
					</div>
					<div class=" slider-control">
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">Отличный стул</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> 2585.9 <span>руб</span></p>
                <a href="#" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>Расположитесь комфортно.</p>
                    <p>Отличное качество материалов
                        позволит вам это.</p>
                    <p>Различные цвета</p>
                    <p>высочайший уровень
                        эргономики и прочность.</p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>

            </div>
        </div>
    </div>
{% endblock %}